spring:
  datasource:
    url: jdbc:h2:mem:product-db
    username: sa
    password:
  jpa:
    datasource-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console